# Generated by Django 4.0 on 2023-11-17 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_user_blocked'),
        ('products', '0003_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='delivery_agent',
            field=models.ForeignKey(blank=True, limit_choices_to={'delivery_agent': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='account.account'),
        ),
    ]
