# Generated by Django 4.0 on 2023-11-17 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_user_blocked'),
        ('products', '0004_alter_orders_delivery_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'orders': True}, on_delete=django.db.models.deletion.CASCADE, related_name='customer_order', to='account.account'),
        ),
    ]
